version: '3.9'

services:
  database:
    image: postgres:14
    container_name: database
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
